//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipt_Project_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Resume
    {
        public int id { get; set; }
        public string Raw_text { get; set; }
        public string Formated_text { get; set; }
        public int user_id { get; set; }
        public string Predicted_labels { get; set; }
        public string filepath { get; set; }
        public HttpPostedFileBase UploadFile { get; set; }
    }
}
