//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPT_Project_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_post
    {
        public int Job_id { get; set; }
        public string Job_description { get; set; }
        public string Job_designation { get; set; }
        public int Employer_id { get; set; }
    }
}
